# Generated by Django 5.1.1 on 2024-09-11 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='verification_code',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='verification_code_last_sent_at',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='verification_code_sent_at',
        ),
    ]
