# Generated by Django 5.1.1 on 2024-09-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_useraccount_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='token',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
