# Generated by Django 5.1.1 on 2024-09-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_useraccount_code_useraccount_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
