# Generated by Django 5.1.1 on 2024-09-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_useraccount_code_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='image',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
