# Generated by Django 5.1.1 on 2024-09-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_useraccount_image_alter_useraccount_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/users'),
        ),
    ]
